FROM ruby:2.6.0

WORKDIR /app

COPY . .

RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash && \
    apt-get install -y nodejs && \
    apt-get purge -y --auto-remove curl && \
    bundle install && \
    rails db:migrate && \
    rake assets:precompile && \
    useradd -m ruby && \
    chown -R ruby .

USER ruby

CMD [ "rails", "s" ]