FROM node:lts-slim

ENV FRONT_URL="http://localhost:5000"

WORKDIR /usr/app
COPY . .

RUN npm install && \
    rm -rf /var/lib/apt/lists/* && \
    chown -R node .
    
USER node

EXPOSE 8000
CMD [ "node", "index.js" ]